packages:
  - packages/*
  - playground
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@babel/core': ^7.26.10
  '@babel/runtime': ^7.27.0
  '@codemirror/lang-css': ^6.3.1
  '@codemirror/lang-html': ^6.4.9
  '@codemirror/lang-javascript': ^6.2.3
  '@codemirror/lang-xml': ^6.1.0
  '@dcloudio/types': ^3.4.14
  '@dcloudio/uni-app': 3.0.0-4010520240507001
  '@dcloudio/uni-app-plus': 3.0.0-4010520240507001
  '@dcloudio/uni-automator': 3.0.0-4010520240507001
  '@dcloudio/uni-cli-shared': 3.0.0-4010520240507001
  '@dcloudio/uni-components': 3.0.0-4010520240507001
  '@dcloudio/uni-h5': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-alipay': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-baidu': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-kuaishou': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-lark': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-qq': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-toutiao': 3.0.0-4010520240507001
  '@dcloudio/uni-mp-weixin': 3.0.0-4010520240507001
  '@dcloudio/uni-quickapp-webview': 3.0.0-4010520240507001
  '@dcloudio/vite-plugin-uni': 3.0.0-4010520240507001
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/tabler': ^1.2.17
  '@tarojs/cli': 3.6.28
  '@tarojs/components': 3.6.28
  '@tarojs/helper': 3.6.28
  '@tarojs/plugin-framework-vue3': 3.6.28
  '@tarojs/plugin-html': 3.6.28
  '@tarojs/plugin-platform-alipay': 3.6.28
  '@tarojs/plugin-platform-jd': 3.6.28
  '@tarojs/plugin-platform-qq': 3.6.28
  '@tarojs/plugin-platform-swan': 3.6.28
  '@tarojs/plugin-platform-tt': 3.6.28
  '@tarojs/plugin-platform-weapp': 3.6.28
  '@tarojs/router': 3.6.28
  '@tarojs/runtime': 3.6.28
  '@tarojs/shared': 3.6.28
  '@tarojs/taro': 3.6.28
  '@tarojs/taro-h5': 3.6.28
  '@tarojs/webpack5-runner': 3.6.28
  '@types/node': ^22.13.17
  '@types/splitpanes': ^2.2.6
  '@types/webpack-env': ^1.18.8
  '@unocss/autocomplete': ^66.3.0
  '@unocss/core': ^66.3.0
  '@unocss/eslint-config': ^66.3.0
  '@unocss/preset-attributify': ^66.3.0
  '@unocss/preset-icons': ^66.3.0
  '@unocss/preset-mini': ^66.3.0
  '@unocss/preset-wind3': ^66.3.0
  '@unocss/preset-wind4': ^66.3.0
  '@unocss/reset': ^66.3.0
  '@unocss/webpack': ^66.3.0
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/babel-plugin-jsx': ^1.4.0
  '@vue/compiler-sfc': ^3.5.13
  '@vueuse/core': ^13.0.0
  ano-ui: ^0.9.2
  babel-preset-taro: 3.6.28
  bumpp: ^10.1.0
  codemirror: ^6.0.1
  codemirror-theme-vars: ^0.1.2
  css-loader: 6.8.1
  eslint: ^9.23.0
  esno: ^4.8.0
  lint-staged: ^15.5.0
  lz-string: ^1.5.0
  magic-string: ^0.30.17
  postcss: ^8.5.3
  sass: ^1.86.1
  simple-git-hooks: ^2.12.1
  splitpanes: ^4.0.3
  style-loader: 3.3.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  vite: ^6.2.4
  vite-plugin-inspect: ^11.0.0
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-i18n: ^11.1.2
  vue-loader: ^17.4.2
  webpack: 5.89.0
