packages:
  - packages/*
  - playground
  - examples/*

catalog:
  unocss-applet: ^0.11.0

catalogMode: prefer

catalogs:
  css:
    css-loader: 6.8.1
    postcss: ^8.5.3
    sass: ^1.86.1
  eslint:
    '@antfu/eslint-config': ^4.11.0
    eslint: ^9.23.0
  icons:
    '@iconify-json/tabler': ^1.2.23
  types:
    '@types/node': ^22.13.17
    '@types/splitpanes': ^2.2.6
  typescript:
    typescript: ^5.8.2
  ui:
    ano-ui: ^0.9.2
  unocss:
    '@unocss/autocomplete': ^66.4.0
    '@unocss/core': ^66.4.0
    '@unocss/eslint-config': ^66.4.0
    '@unocss/preset-attributify': ^66.4.0
    '@unocss/preset-icons': ^66.4.0
    '@unocss/preset-mini': ^66.4.0
    '@unocss/preset-wind3': ^66.4.0
    '@unocss/preset-wind4': ^66.4.0
    '@unocss/reset': ^66.4.0
    '@unocss/vite': 66.0.0
    '@unocss/webpack': ^66.4.0
    unocss: ^66.4.0
  utils:
    '@shikijs/monaco': ^3.9.2
    bumpp: ^10.1.0
    esno: ^4.8.0
    lint-staged: ^15.5.0
    lz-string: ^1.5.0
    magic-string: ^0.30.17
    monaco-editor: ^0.52.2
    shiki: ^3.9.2
    simple-git-hooks: ^2.12.1
    splitpanes: ^4.0.3
    unbuild: ^3.5.0
  vite:
    '@vitejs/plugin-vue': ^5.2.3
    vite: ^5.2.8
    vite-plugin-inspect: ^11.0.0
    vitest: ^3.1.1
  vue:
    '@vue/babel-plugin-jsx': ^1.4.0
    '@vue/compiler-sfc': ^3.5.13
    '@vueuse/core': ^13.0.0
    pinia: ^3.0.3
    vue: ^3.5.13
    vue-i18n: ^11.1.2
    vue-loader: ^17.4.2
