name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          require-lockfile: true

      - run: pnpx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
